### ISSUE TITLE
Question about training parameters

### ISSUE THREAD

**Issue by Yingjuan** [Milan-BUAA/TSAN-brain-age-estimation#9]
Dear authors, the training scripts load weights from TSAN/TSAN-brain-age-estimation/TSAN/Sodeep_pretrain_weight.
Does it mean that we transfer knowledge from the pre-trained model and fine-tune the model based on our data, instead of training a new model from scratch? 

In addition, it seems that only two batch sizes are allowed for training, 8 and 32. Could you advise which one to choose?
Thank you!

**Comment by liuziyang1106** [comment]
Thanks for your attention.
In fact, the Sodeep model trains a proxy differentiable network as an approximation of the rank operator, instead of brain age estimation.
Our TSAN brain age estimation pretrained model downloaded links is https://bhpan.buaa.edu.cn/link/AAE3C4E359A06847689058F267346E73A8, which is also noted in the README document.
As you said, if you load our pre-trained TSAN model, you are using some prior knowledge from the data set described in our paper.
Currently, we only offer two batch size options(8 and 32), which one to use depends on your computing resources. We will provide more batch size selection of Sodeep pre-trained models next week.

**Comment by Yingjuan** [comment]
I appreciate your detailed explanation! I plan to utilize your provided training scripts to train the model with my own data. I'm curious about the initialization of the weights. Is it possible to begin with the weights from your pre-trained model and then fine-tune it based on my data? Thanks once more for your assistance!

**Comment by liuziyang1106** [comment]
Of course, you can fine-tune the model based on the released pretrain weights, you only need to modify the training scripts and main code file to load pretrain weights and fine-tuning.

**Comment by Yingjuan** [comment]
Thank you for the information!
